# Generated by Django 6.0.2 on 2026-03-06 16:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='education',
            field=pgvector.django.vector.VectorField(dimensions=1536),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience',
            field=pgvector.django.vector.VectorField(dimensions=1536),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='skill',
            field=pgvector.django.vector.VectorField(dimensions=1536),
            preserve_default=False,
        ),
    ]
