# Generated by Django 6.0.2 on 2026-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobdescription_education_jobdescription_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="education_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="experience_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="skill_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
