# Generated by Django 6.0.2 on 2026-03-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_searchrun'),
        ('core', '0004_jobdescription_split_text_fields'),
    ]

    operations = [
    ]
