# Generated by Django 6.0.2 on 2026-03-09 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260309_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='searchrun',
            name='job_description_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
